version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10

  - package-ecosystem: "cargo"
    directory: "/packages/contracts"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "contracts"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10 