# Configuração do projeto
project_id: "yieldswap"
api_token_env: "CROWDIN_API_TOKEN"
base_path: "."
base_url: "https://api.crowdin.com"

# Arquivos para tradução
files:
  - source: "/apps/web/public/locales/en/common.json"
    translation: "/apps/web/public/locales/%two_letters_code%/common.json"
    languages_mapping:
      two_letters_code:
        pt-BR: "pt"
        es-ES: "es"
    export_languages:
      - "pt"
      - "es"

  - source: "/apps/web/public/locales/en/*.json"
    translation: "/apps/web/public/locales/%two_letters_code%/%original_file_name%"
    languages_mapping:
      two_letters_code:
        pt-BR: "pt"
        es-ES: "es"
    export_languages:
      - "pt"
      - "es"

# Configurações de preservação
preserve_hierarchy: true

# Configurações de exportação
export_options:
  json:
    format: "ICU"
    indent: 2

# Configurações de atualização
update_option: "update_as_unapproved"
commit_message: "chore: update %language% translations" 